name: Build_Dylib

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Setup SDK
        run: |
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          tar -xf iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks

      - name: Prepare and Build
        run: |
          # هذا السطر يبحث عن أي ملف ينتهي بـ .x ويحوله لـ Tweak.x ليتوافق مع الـ Makefile
          find . -name "*.x" -exec mv {} Tweak.x \;
          
          export THEOS=~/theos
          make clean
          make FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Shield_Dylib
          path: .theos/obj/main/*.dylib
