name: Build Pro Max Shield

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        run: brew install ldid xz
      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master ~/theos/sdks
          rm master.zip
      - name: Build
        run: |
          export THEOS=~/theos
          make clean
          make messages=yes
      - name: Prepare Artifact
        run: |
          mkdir -p build_output
          # نظام بحث ذكي لحل مشكلة exit code 1 وتغير الأسماء
          find .theos/obj -name "*.dylib" -exec cp {} build_output/ \;
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Pro-Max-Final-Dylib
          path: build_output/
