name: Build_Security_Dylib

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Setup SDK
        run: |
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          tar -xf iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks

      - name: Fix Filenames and Build
        run: |
          # البحث عن أي ملف .x وتحويله لـ Tweak.x حتى لو كان فيه مسافات
          find . -name "*.x" -exec mv "{}" Tweak.x \;
          
          export THEOS=~/theos
          make clean
          make FINALPACKAGE=1

      - name: Upload Dylib
        uses: actions/upload-artifact@v3
        with:
          name: SecurityShield_Final
          path: packages/*.dylib || .theos/obj/main/*.dylib || .theos/obj/*.dylib
