name: Build_Security_Dylib

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=/Users/runner/theos" >> $GITHUB_ENV

      - name: Setup SDK (The Professional Way)
        run: |
          # هذه الأداة تجلب الـ SDK بشكل آمن ومباشر من مستودعات ذايوس الرسمية
          git clone --quiet https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build Dylib
        run: |
          export THEOS=/Users/runner/theos
          # التنظيف وبدء البناء مع تحديد الـ SDK الموجود فعلياً
          make clean
          make FINALPACKAGE=1 SDKVERSION=14.5
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SecurityShield_Dylib
          path: .theos/obj/main/*.dylib
