name: Build Safe Shield Pro

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install ldid xz

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master ~/theos/sdks
          rm master.zip

      - name: Build Tweak
        run: |
          export THEOS=~/theos
          make clean
          make messages=yes

      - name: Prepare Artifact
        run: |
          mkdir -p build_output
          # نظام بحث ذكي لضمان استخراج الملف بنجاح مهما كان اسمه
          find .theos/obj -name "*.dylib" -exec cp {} build_output/ \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GCloudShield-Safe-Edition
          path: build_output/
