name: Build V63.1 Global

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: brew install ldid xz

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Setup SDK (Fixed)
        run: |
          rm -rf ~/theos/sdks
          git clone https://github.com/theos/sdks.git ~/theos/sdks

      - name: Build Global
        run: |
          export THEOS=~/theos
          make clean all FINALPACKAGE=1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: V63-Global-Protection
          path: .theos/obj/**/CoreAudioSupport.framework/
